resource_group_name = "mysqlResourceGroup"
location = "westeurope"
db_name = "mydatabase"
admin_username = "azureuser"
password = "P@ssw0rd12345!"
start_ip_address = "0.0.0.0"
end_ip_address = "255.255.255.255"
ssl_enforcement = "Disabled"